---
- name: Medidas de seguridad en Ubuntu
  hosts: Ubuntu
  become: true
  tasks:
    - name: Habilitar UFW
      community.general.ufw:
        state: enabled
        default: deny
        direction: incoming

    - name: Permitir SSH
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Chequear clave pública de sysadmin
      ansible.posix.authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Deshabilitar autenticación por contraseña en SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Reiniciar SSH

  handlers:
    - name: Reiniciar SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
